import React,{useEffect,useState} from "react";
import {createRoot} from "react-dom/client";
import {LineChart,Line,XAxis,YAxis,Tooltip,ResponsiveContainer} from "recharts";
import "./style.css";
const API=import.meta.env.VITE_API_URL||"http://127.0.0.1:8000";
const demoHistory=[{t:"10:00",hr:96,spo2:97},{t:"10:02",hr:101,spo2:96},{t:"10:04",hr:108,spo2:95},{t:"10:06",hr:112,spo2:93},{t:"10:08",hr:118,spo2:91}];
function App(){
 const [logged,setLogged]=useState(localStorage.getItem("logged")==="1");
 const [page,setPage]=useState("Dashboard"); const [data,setData]=useState(null); const [alerts,setAlerts]=useState([]); const [dark,setDark]=useState(true);
 const load=async()=>{try{let [v,a,p]=await Promise.all([fetch(API+"/api/vitals"),fetch(API+"/api/alerts"),fetch(API+"/api/patients")]);let vv=await v.json(),aa=await a.json();setData({v:vv[0],patients:await p.json()});setAlerts(aa)}catch(e){console.log(e)}};
 useEffect(()=>{if(logged)load()},[logged]);
 useEffect(()=>{if(!logged)return;let ws;try{ws=new WebSocket(API.replace("http","ws")+"/ws");ws.onmessage=()=>load()}catch{};return()=>ws?.close()},[logged]);
 if(!logged)return <Login onLogin={()=>{localStorage.setItem("logged","1");setLogged(true)}}/>;
 const v=data?.v||{}; const patient=data?.patients?.find(p=>p.id===v.patient_id)||data?.patients?.[0]||{};
 const risk=calc(v); 
 return <div className={dark?"app dark":"app"}><aside><div className="brand">🚑 <span>Smart<br/><small>Ambulance</small></span></div><nav>{["Dashboard","Patient Monitoring","Ambulance Tracking","Emergency Alerts","Patient History","Ambulance Management","Settings"].map(x=><button className={page===x?"active":""} onClick={()=>setPage(x)}>{x}</button>)}</nav><button className="logout" onClick={()=>{localStorage.removeItem("logged");setLogged(false)}}>Logout</button></aside>
 <main><header><div><div className="eyebrow">HOSPITAL COMMAND CENTER</div><h1>{page}</h1></div><div className="head-actions"><button onClick={()=>setDark(!dark)}>☾</button><span className="online">● System Online</span></div></header>
 {page==="Dashboard"&&<Dashboard v={v} risk={risk} alerts={alerts} patient={patient} onDemo={async s=>{await fetch(API+"/api/demo/"+s,{method:"POST"});load()}}/>}
 {page==="Patient Monitoring"&&<Monitoring v={v} patient={patient} risk={risk}/>}
 {page==="Ambulance Tracking"&&<Tracking v={v}/>}
 {page==="Emergency Alerts"&&<Alerts alerts={alerts}/>}
 {page==="Patient History"&&<History/>}
 {page==="Ambulance Management"&&<Ambulances/>}
 {page==="Settings"&&<Settings/>}
 <footer>Educational prototype • Synthetic patient data • Not a certified medical device</footer></main></div>
}
function calc(v){let s=0,r=[];if(v.spo2<90){s+=40;r.push("Low SpO₂")}else if(v.spo2<94){s+=25;r.push("Reduced SpO₂")}if(v.heart_rate>120||v.heart_rate<50){s+=25;r.push("Abnormal heart rate")}else if(v.heart_rate>100){s+=10;r.push("Elevated heart rate")}if(v.temperature>=39){s+=20;r.push("High temperature")}else if(v.temperature>=38){s+=10;r.push("Elevated temperature")}if(v.respiratory_rate>30||v.respiratory_rate<10){s+=20;r.push("Abnormal respiratory rate")}else if(v.respiratory_rate>20){s+=10;r.push("Increased respiratory rate")}return {score:Math.min(100,s),level:s>=75?"CRITICAL":s>=50?"HIGH":s>=25?"MEDIUM":"LOW",reasons:r}}
function Login({onLogin}){const [e,setE]=useState("demo@hospital.com"),[p,setP]=useState("demo123"),[err,setErr]=useState("");return <div className="login"><div className="login-card"><div className="logo-big">🚑</div><div className="eyebrow">HOSPITAL PRE-ALERT</div><h1>Smart Ambulance</h1><p>Secure emergency operations dashboard</p><input value={e} onChange={x=>setE(x.target.value)} placeholder="Email"/><input value={p} onChange={x=>setP(x.target.value)} type="password" placeholder="Password"/><button className="primary" onClick={async()=>{let r=await fetch(API+"/api/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:e,password:p})});r.ok?onLogin():setErr("Use demo@hospital.com / demo123")}}>Sign in</button><button onClick={onLogin}>Demo Login</button>{err&&<small className="danger">{err}</small>}</div></div>}
function Stats({v,risk,alerts}){return <div className="stats"><Card label="Active Ambulances" value="1" icon="🚑"/><Card label="Active Patients" value="1" icon="👤"/><Card label="Critical Patients" value={risk.level==="CRITICAL"?"1":"0"} icon="🚨"/><Card label="Average ETA" value="12 min" icon="⏱"/></div>}
function Card({label,value,icon}){return <div className="stat"><span>{icon}</span><div><small>{label}</small><strong>{value}</strong></div></div>}
function Dashboard({v,risk,alerts,patient,onDemo}){return <><Stats v={v} risk={risk} alerts={alerts}/><div className="grid2"><section className="panel"><div className="panel-title"><h2>Live Ambulances</h2><span className={"badge "+risk.level.toLowerCase()}>{risk.level}</span></div><table><thead><tr><th>Ambulance</th><th>Patient</th><th>SpO₂</th><th>Heart Rate</th><th>ETA</th><th>Status</th></tr></thead><tbody><tr><td>AMB-01</td><td>{patient.id||"P001"}</td><td>{v.spo2}%</td><td>{v.heart_rate} BPM</td><td>12 min</td><td><span className="status">● En Route</span></td></tr></tbody></table></section><section className="panel"><h2>Demo Mode</h2><p>Test the complete workflow without ESP32 hardware.</p><div className="demo-buttons">{["normal","medium","high","critical"].map(s=><button onClick={()=>onDemo(s)}>{s}</button>)}</div><button className="emergency" onClick={()=>onDemo("critical")}>🚨 Simulate Emergency</button></section></div><div className="grid2"><section className="panel"><h2>Current Patient</h2><div className="vitals">{vital("Heart Rate",v.heart_rate,"BPM")} {vital("SpO₂",v.spo2,"%")} {vital("Temperature",v.temperature,"°C")} {vital("Resp. Rate",v.respiratory_rate,"/min")}</div></section><section className="panel"><h2>AI-Assisted Risk Assessment</h2><div className="riskbig"><strong>{risk.score}%</strong><span className={"badge "+risk.level.toLowerCase()}>{risk.level}</span></div><p>{risk.reasons.length?risk.reasons.join(" • "):"No abnormal factors detected."}</p><small>Decision support only; not a medical diagnosis.</small></section></div></>}
function vital(n,x,u){return <div className="vital"><small>{n}</small><strong>{x??"--"}</strong><span>{u}</span></div>}
function Monitoring({v,patient,risk}){return <><div className="grid2"><section className="panel"><h2>Patient Profile</h2><div className="profile"><b>{patient.name}</b><span>ID: {patient.id}</span><span>{patient.age} years • {patient.gender}</span><span>{patient.emergency_type}</span><span>Ambulance: {patient.ambulance_id}</span></div></section><section className="panel"><h2>Live Vitals</h2><div className="vitals">{vital("Heart Rate",v.heart_rate,"BPM")}{vital("SpO₂",v.spo2,"%")}{vital("Temperature",v.temperature,"°C")}{vital("Resp. Rate",v.respiratory_rate,"/min")}</div></section></div><section className="panel"><h2>Vital Trend</h2><ResponsiveContainer width="100%" height={280}><LineChart data={demoHistory}><XAxis dataKey="t"/><YAxis/><Tooltip/><Line type="monotone" dataKey="hr" strokeWidth={3}/><Line type="monotone" dataKey="spo2" strokeWidth={3}/></LineChart></ResponsiveContainer></section><section className="panel"><h2>ECG Waveform</h2><div className="ecg">{Array.from({length:80},(_,i)=><i key={i} style={{height:(20+Math.abs(Math.sin(i*.7))*45+(i%17===0?40:0))+"px"}}/> )}</div></section></>}
function Tracking({v}){return <><section className="panel"><h2>Ambulance Tracking</h2><div className="map"><div className="route"/><div className="pin p1">🚑</div><div className="pin p2">🏥</div></div><div className="tracking-grid"><b>AMB-01<small>Ambulance</small></b><b>48 km/h<small>Speed</small></b><b>7.2 km<small>Distance</small></b><b>12 min<small>ETA</small></b></div></section></>}
function Alerts({alerts}){return <section className="panel"><div className="panel-title"><h2>Emergency Alerts</h2><span className="badge critical">{alerts.length} Alerts</span></div>{alerts.length===0?<p>No active alerts.</p>:<table><thead><tr><th>Time</th><th>Patient</th><th>Ambulance</th><th>Level</th><th>Message</th></tr></thead><tbody>{alerts.map(a=><tr><td>{new Date(a.timestamp).toLocaleTimeString()}</td><td>{a.patient_id}</td><td>{a.ambulance_id}</td><td><span className="badge critical">{a.level}</span></td><td>{a.message}</td></tr>)}</tbody></table>}</section>}
function History(){return <section className="panel"><h2>Patient History</h2><table><thead><tr><th>Time</th><th>HR</th><th>SpO₂</th><th>Temperature</th><th>Resp. Rate</th><th>Risk</th></tr></thead><tbody>{demoHistory.map((x,i)=><tr><td>{x.t}</td><td>{x.hr}</td><td>{x.spo2}%</td><td>{i<2?"36.8":"38.1"}°C</td><td>{i<2?16:24}</td><td><span className={"badge "+(i>3?"high":"medium")}>{i>3?"HIGH":"MEDIUM"}</span></td></tr>)}</tbody></table></section>}
function Amb(){return <section className="panel"><h2>Ambulance Management</h2><table><thead><tr><th>ID</th><th>Registration</th><th>Driver</th><th>Status</th><th>Patient</th><th>Destination</th></tr></thead><tbody><tr><td>AMB-01</td><td>MH-00-AA-0001</td><td>Demo Driver</td><td><span className="status">En Route</span></td><td>P001</td><td>City General Hospital</td></tr><tr><td>AMB-02</td><td>MH-00-BB-0002</td><td>Demo Driver 2</td><td>Available</td><td>P002</td><td>City General Hospital</td></tr></tbody></table></section>}
function Ambulances(){return <Amb/>}
function Settings(){return <section className="panel"><h2>Settings</h2><div className="settings"><label>Hospital Name<input value="City General Hospital" readOnly/></label><label>MQTT Broker<input placeholder="Configured in backend .env"/></label><label>API Endpoint<input value={API} readOnly/></label><label>Security<input value="JWT + HTTPS-ready" readOnly/></label></div></section>}
createRoot(document.getElementById("root")).render(<App/>);